"""add jira knowledge table

Revision ID: 6e8ea9393a5e
Revises: 
Create Date: 2025-12-17 19:16:14.034597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8ea9393a5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_knowledge',
    sa.Column('issue_key', sa.String(), nullable=False, comment='Jira Issue Key (e.g. PAY-001)'),
    sa.Column('issue_type', sa.String(), nullable=False, comment='Type: Epic, Story, Task, Bug'),
    sa.Column('parent_key', sa.String(), nullable=True, comment='Parent Issue Key (e.g. PAY-001)'),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('business_logic', sa.Text(), nullable=True, comment='Summarized Business Rules & Logic'),
    sa.Column('technical_spec', sa.Text(), nullable=True, comment='Technical constraints, API, DB details'),
    sa.Column('test_scenarios', sa.Text(), nullable=True, comment='Test cases and acceptance criteria'),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('issue_key')
    )
    op.create_index(op.f('ix_jira_knowledge_issue_key'), 'jira_knowledge', ['issue_key'], unique=False)
    op.create_index(op.f('ix_jira_knowledge_issue_type'), 'jira_knowledge', ['issue_type'], unique=False)
    op.create_index(op.f('ix_jira_knowledge_parent_key'), 'jira_knowledge', ['parent_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jira_knowledge_parent_key'), table_name='jira_knowledge')
    op.drop_index(op.f('ix_jira_knowledge_issue_type'), table_name='jira_knowledge')
    op.drop_index(op.f('ix_jira_knowledge_issue_key'), table_name='jira_knowledge')
    op.drop_table('jira_knowledge')
    # ### end Alembic commands ###
