"""add issue links

Revision ID: c6d457cf4b3b
Revises: 6e8ea9393a5e
Create Date: 2025-12-18 13:52:27.231728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6d457cf4b3b'
down_revision: Union[str, Sequence[str], None] = '6e8ea9393a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jira_knowledge', sa.Column('issue_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='List of related issues (blocks, relates to)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jira_knowledge', 'issue_links')
    # ### end Alembic commands ###
